### ISSUE TITLE
Unhandled Promise Reject Warning

### ISSUE THREAD

**Issue by eshimischi** [kwonoj/hunspell-asm#167]
Hi, 
my Node.js version is 8.12.0
i got this message after did npm install:

`node -r ts-node/register bootstrap.ts`
`(node:2408) UnhandledPromiseRejectionWarning: 1`
`(node:2408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)`
`(node:2408) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.`

any fixes or ideas how to solve it?

**Comment by kwonoj** [comment]
Bootstrap relies on most behavior via external binary (wget, sha512) and I presume there's some failure. Try to ensure those are available and if still fails try to catch / grab error messages for detail.

**Comment by kwonoj** [comment]
closing issue as at least no longer leave rejection unhandled, it'll write out to console instead.
