### ISSUE TITLE
"nanoid is not a function" in 2.0.0

### ISSUE THREAD

**Issue by goyney** [kwonoj/hunspell-asm#186]
Looks like there is an issue in the 2.0.0 release:

```
hunspellLoader.js:21 Uncaught (in promise) TypeError: nanoid is not a function
    at exports.hunspellLoader (hunspellLoader.js:21)
    at timeout (loadModule.js:29)
    at getModuleLoader.js:37
    at step (tslib.es6.js:97)
    at Object.next (tslib.es6.js:78)
    at fulfilled (tslib.es6.js:68)
```

**Comment by kwonoj** [comment]
Would you mind share reproducible repo to take a look? I'm using same version on my prod application failed to repro this.

**Comment by goyney** [comment]
I'll have to whip one up later tonight, I do not have anything sharable at the moment.

**Comment by kwonoj** [comment]
Thanks. rough hunch is this may related with importing default export and application's configuration around those, it'll be helpful if I can reproduce it.

**Comment by goyney** [comment]
I can share that we are currently on 1.1.2 and it works fine. I don't see anything in the breaking changes that would affect us. We do, however, use Parcel currently as our bundler and it is not the greatest. It is possible something is happening there.

**Comment by kwonoj** [comment]
Bundler plays a lot of rules around import scenarios, so I think it is possible some of build config affects it. I just tried latest with plain node.js doesn't invoving any bundler, and it works fine to load to deps.

**Comment by kwonoj** [comment]
so far it's hard to tell if this is bundler config of actual issue (I'm using with bundler without problem currently), tentatively closing. feel free to reopen / create new issue if there's minimal repro I can try.

**Comment by goyney** [comment]
Nah, closing this is fine if no one else is seeing the issue. We've since moved off of Parcel and on to Webpack and have no issues with the latest release. My apologizes for not updating and closing this issue earlier. Thank you!
