### ISSUE TITLE
Low performance of "suggest" method

### ISSUE THREAD

**Issue by avsokolov** [kwonoj/hunspell-asm#196]
My code:
```
//load module here
import { loadModule } from 'hunspell-asm';

const aff = await fetch(affPath);
const affBuffer = new Uint8Array(await aff.arrayBuffer());
const affFile = hunspellFactory.mountBuffer(affBuffer);

const dic = await fetch(dicPath);
const dicBuffer = new Uint8Array(await dic.arrayBuffer());
const dictFile = hunspellFactory.mountBuffer(dicBuffer);

const hunspell = hunspellFactory.create(affFile, dictFile);
hunspellFactory.unmount(affFile);
hunspellFactory.unmount(dictFile);

function getSuggestions(word) {
    const now = performance.now();
    const suggestions = hunspell.suggest(word);
    console.log('hunspell.suggest duration: ${Math.round(performance.now()-now)}ms`);
    return suggestions;
}

//usage with a spanish dictionary
getSuggestions('romanización'); //console: hunspell.suggest duration ~850ms

//usage with a french dictionary
getSuggestions('ambiguïté'); //console: hunspell.suggest duration ~620ms
getSuggestions('contiguïté'); //console: hunspell.suggest duration ~650ms
```

I use the latest chrome on windows pc (Core i7@3.40GHz)

Is it possible to research low-performance reason or bottlenecks? Maybe it relates to the emscripten build options?

**Comment by kwonoj** [comment]
I believe this is due to workaround https://github.com/kwonoj/hunspell-asm/issues/187 optimzation of binary turned off. I have plan to one major breaking bump to enable optimization and only support browser doesn't have those proble (of fixes known wasm handling issue), hope that'll resolve most cases.

**Comment by kwonoj** [comment]
@avsokolov one thing to note is getting suggestion is generally slow operation and lot vary based on dict / affix rules as well, I wouldn't be very surprised it's still somewhat slow after enabling optimization.
